name: Reusable workflow
on:
  workflow_call:
    inputs:
       who-to-greet:
         type: string
         required: true
         default: 'word'
jobs: 
  reusable-job:
  runs-on: ubuntu-latest
    steps:
        run: echo "Hello ${{ inputs.who-to-greet }}"
  outputs:
        current-time:
          description: 'The time when greeting.'
          value: ${{ jobs.reusable-job.outputs.current-time }}
  
    
